# see here
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
#
name: SampleApplication-iOS # TODO Project name

include: [environments.yml]
#include: [environments.yml, code_format.yml]

# TODO move to code_format.yml & include, and swift lint
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  groupSortPosition: top # or none, bottom
  transitivelyLinkDependencies: false
  preGenCommand: ./Scripts/GenerateProjectPhases/preGenCommand.sh
  postGenCommand: ./Scripts/GenerateProjectPhases/postGenCommand.sh

attributes:
  ORGANIZATIONNAME: Takahiro Tsuchiya

# TODO move to environments.yml
configs:
  Base: base
  Debug: debug
  Beta: beta
  Demo: demo

configFiles:
  Base: Configurations/Config.base.xcconfig
  Debug: Configurations/Config.debug.xcconfig
  Beta: Configurations/Config.beta.xcconfig
  Demo: Configurations/Config.demo.xcconfig

settings:
  base: # TODO move to xcconfig
    SWIFT_VERSION: 5.2  # TODO update 5.2
    IPHONEOS_DEPLOYMENT_TARGET: 13.4  # TODO upadate 13.4.1
    CURRENT_PROJECT_VERSION: 0.0.00

#settingGroups:

targets:
  App:
    type: application # or app-extension, bundle, framework
    platform: iOS # or tvOS, macOS, watchOS in array
    deploymentTarget: 13.4 # TODO upadate 13.4
    sources:
      - path: App
        name: App
      - GoogleService-Info.plist # TODO using bitrise, step to create files script
      - Configurations/Config.base.xcconfig # TODO config file include not add project
      # Don't use "Resources"
      # TODO rename
      - path: AssetsResources
        name: AssetsResources
    dependencies:
      # Don't add Firebase.framework
      - carthage: FIRAnalyticsConnector
        linkType: staticBinary
      - carthage: FirebaseAnalytics
        linkType: staticBinary
      - carthage: FirebaseCore
        linkType: staticBinary
      - carthage: FirebaseCoreDiagnostics
        linkType: staticBinary
      - carthage: FirebaseInstallations
        linkType: staticBinary
      - carthage: GoogleAppMeasurement
        linkType: staticBinary
      - carthage: GoogleDataTransport
        linkType: staticBinary
      - carthage: GoogleDataTransportCCTSupport
        linkType: staticBinary
      - carthage: GoogleUtilities
        linkType: staticBinary
      - carthage: nanopb
        linkType: staticBinary
      - carthage: PromisesObjC
        linkType: staticBinary
      - sdk: StoreKit.framework
      - sdk: libc++.tbd
      - sdk: libsqlite3.tbd
      - sdk: AdSupport.framework

#fileGroups:
#  - README.md

schemes:
  SampleApplication-iOS Beta: # TODO change your app's name
    templates:
      - CommonSchemeTemplates
    run:
      config: Beta # TODO same configs
    test:
      config: Beta
    profile:
      config: Beta
    analyze:
      config: Beta
    archive:
      config: Beta

  SampleApplication-iOS Debug: # TODO change your app's name
    templates:
      - CommonSchemeTemplates
    run:
      config: Debug # TODO same configs
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug

  SampleApplication-iOS Demo: # TODO change your app's name
    templates:
      - CommonSchemeTemplates
    run:
      config: Demo # TODO same configs
    test:
      config: Demo
    profile:
      config: Demo
    analyze:
      config: Demo
    archive:
      config: Demo

schemeTemplates:
  CommonSchemeTemplates:
    templates:
      - buildScheme
      - runScheme
      - testScheme
      - profileScheme
      - analyzeScheme
      - archiveScheme

  buildScheme:
    build:
      targets:
        App: all

  runScheme:
    run:
      config: Base # TODO same configs
      commandLineArguments:
        -FIRDebugEnabled: YES
        -FIRDebugDisabled: NO
        -FIRAnalyticsDebugEnabled: YES
        -FIRAnalyticsDebugDisabled: NO
        -FIRAnalyticsVerboseLoggingEnabled: YES
        -FIRAnalyticsVerboseLoggingDisabled: NO

  testScheme:
    test:
      config: Base
      commandLineArguments:
        -FIRDebugEnabled: YES
        -FIRDebugDisabled: NO
        -FIRAnalyticsDebugEnabled: YES
        -FIRAnalyticsDebugDisabled: NO
        -FIRAnalyticsVerboseLoggingEnabled: YES
        -FIRAnalyticsVerboseLoggingDisabled: NO
      gatherCoverageData: true

  profileScheme:
    profile:
      config: Base
      commandLineArguments:
        -FIRDebugEnabled: NO
        -FIRDebugDisabled: YES
        -FIRAnalyticsDebugEnabled: NO
        -FIRAnalyticsDebugDisabled: YES
        -FIRAnalyticsVerboseLoggingEnabled: NO
        -FIRAnalyticsVerboseLoggingDisabled: YES

  analyzeScheme:
    analyze:
      config: Base

  archiveScheme:
    archive:
      config: Base
      revealArchiveInOrganizer: false

#targetTemplates:

#packages:

#localPackages:

#projectReferences:
