# see here
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
#
name: SampleApplication-iOS # TODO Project name

include: [environments.yml]
#include: [environments.yml, code_format.yml]

# TODO move to code_format.yml & include, and swift lint
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  groupSortPosition: top # or none, bottom
  transitivelyLinkDependencies: false
  preGenCommand: ./Scripts/GenerateProjectPhases/preGenCommand.sh
  postGenCommand: ./Scripts/GenerateProjectPhases/postGenCommand.sh

attributes:
  ORGANIZATIONNAME: Takahiro Tsuchiya

# TODO move to environments.yml
configs:
  Base: base

configFiles:
  Base: Configurations/Config.base.xcconfig

settings:
  base: # TODO move to xcconfig
    SWIFT_VERSION: 5.2  # TODO update 5.2
    IPHONEOS_DEPLOYMENT_TARGET: 13.4  # TODO upadate 13.4.1
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    PRODUCT_NAME: "$(PRODUCT_NAME)"
    PRODUCT_DISPLAY_NAME: "$(PRODUCT_DISPLAY_NAME)"
    PRODUCT_BUNDLE_IDENTIFIER: com.sample.SampleApplication-iOS # TODO update your identifier
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CURRENT_PROJECT_VERSION: 0.0.01

#settingGroups:

targets:
  App:
    type: application # or app-extension, bundle, framework
    platform: iOS # or tvOS, macOS, watchOS in array
    deploymentTarget: 13.4 # TODO upadate 13.4
    sources:
      - path: App
        name: App
      - GoogleService-Info.plist # TODO using bitrise, step to create files script
      - Configurations/Config.base.xcconfig # TODO config file include not add project
    dependencies:
      # Don't add Firebase.framework
      - carthage: FIRAnalyticsConnector
        linkType: staticBinary
      - carthage: FirebaseAnalytics
        linkType: staticBinary
      - carthage: FirebaseCore
        linkType: staticBinary
      - carthage: FirebaseCoreDiagnostics
        linkType: staticBinary
      - carthage: FirebaseInstallations
        linkType: staticBinary
      - carthage: GoogleAppMeasurement
        linkType: staticBinary
      - carthage: GoogleDataTransport
        linkType: staticBinary
      - carthage: GoogleDataTransportCCTSupport
        linkType: staticBinary
      - carthage: GoogleUtilities
        linkType: staticBinary
      - carthage: nanopb
        linkType: staticBinary
      - carthage: PromisesObjC
        linkType: staticBinary
      - sdk: StoreKit.framework
      - sdk: libc++.tbd
      - sdk: libsqlite3.tbd
      - sdk: AdSupport.framework

#fileGroups:
#  - README.md

schemes:
  SampleApplication-iOS Debug: # TODO change your app's name
    build:
      targets:
        App: all
    run:
      config: Base # TODO same configs
      commandLineArguments:
        -FIRDebugEnabled: YES
        -FIRAnalyticsDebugEnabled: YES
        -FIRAnalyticsVerboseLoggingEnabled: YES
    test:
      config: Base
      commandLineArguments:
        -FIRDebugEnabled: YES
        -FIRAnalyticsDebugEnabled: YES
        -FIRAnalyticsVerboseLoggingEnabled: YES
      gatherCoverageData: true
    profile:
      config: Base
    analyze:
      config: Base
    archive:
      config: Base
      revealArchiveInOrganizer: false

#targetTemplates:

#packages:

#localPackages:

#projectReferences:
