# see here
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
#
name: SampleApplication-iOS # TODO Project name

include: [environments.yml]
#include: [environments.yml, code_format.yml]

# TODO move to code_format.yml & include, and swift lint
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  groupSortPosition: top # or none, bottom
  transitivelyLinkDependencies: false
  preGenCommand: ./Scripts/GenerateProjectPhases/preGenCommand.sh
  postGenCommand: ./Scripts/GenerateProjectPhases/postGenCommand.sh

attributes:
  LastSwiftUpdateCheck: 1140
  LastUpgradeCheck: 1140
  ORGANIZATIONNAME: Takahiro Tsuchiya

# TODO move to environments.yml
configs:
  Debug: debug
  Beta: beta
  Demo: debug
  Release: release

configFiles:
  Debug: Configurations/Config.debug.xcconfig
  Beta: Configurations/Config.beta.xcconfig
  Demo: Configurations/Config.demo.xcconfig
  Release: Configurations/Config.release.xcconfig

settings:
  base: # TODO move to xcconfig
    SWIFT_VERSION: 5.2  # TODO update 5.2
    IPHONEOS_DEPLOYMENT_TARGET: 13.4  # TODO upadate 13.4.1
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    CODE_SIGN_STYLE: Automatic
    OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC # to use Firebase
    PRODUCT_NAME: "$(PRODUCT_NAME)"
    PRODUCT_DISPLAY_NAME: "$(PRODUCT_DISPLAY_NAME)"
    PRODUCT_BUNDLE_IDENTIFIER: com.sample.SampleApplication-iOS # TODO update your identifier
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    INFOPLIST_FILE: App/Info.plist
#    DEVELOPMENT_TEAM: # TODO update your development team
    CURRENT_PROJECT_VERSION: 0.0.01

#settingGroups:

targets:
#  MyFramework:
#    type: framework # or application, app-extension, bundle
#    platform: [iOS] # or tvOS, macOS, watchOS
#    sources:
#      - path: MyFramework
#        name: MyFramework
  App:
    type: application # or app-extension, bundle, framework
    platform: iOS # or tvOS, macOS, watchOS in array
    deploymentTarget: 13.4 # TODO upadate 13.4
    sources:
      - path: App
        name: App
      - GoogleService-Info.plist # TODO using bitrise, step to create files
    dependencies:
      # Don't add Firebase.framework
      - sdk: StoreKit.framework
      - sdk: libc++.tbd
      - sdk: libsqlite3.tbd
      - sdk: AdSupport.framework
      # uuum, not good
      - framework: Carthage/Build/iOS/Firebase.framework
        embed: false
        link: false
      - framework: Carthage/Build/iOS/FIRAnalyticsConnector.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseABTesting.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseAnalytics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCore.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseCoreDiagnostics.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseInAppMessaging.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseInstallations.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseInstanceID.framework
        embed: false
      - framework: Carthage/Build/iOS/FirebaseMessaging.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleAppMeasurement.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleDataTransport.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleDataTransportCCTSupport.framework
        embed: false
      - framework: Carthage/Build/iOS/GoogleUtilities.framework
        embed: false
      - framework: Carthage/Build/iOS/nanopb.framework
        embed: false
      - framework: Carthage/Build/iOS/PromisesObjC.framework
        embed: false
      - framework: Carthage/Build/iOS/Protobuf.framework
        embed: false

    info:
      path: ./App/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
#        UISupportedInterfaceOrientations~ipad:
#          - UIInterfaceOrientationPortrait
#          - UIInterfaceOrientationPortraitUpsideDown
#          - UIInterfaceOrientationLandscapeLeft
#          - UIInterfaceOrientationLandscapeRight
#        UIRequiredDeviceCapabilities:
#          - armv7

#    preBuildScripts:
#      - script: ./Scripts/BuildPhases/
#      name: SwiftGen
#    preBuildScripts:
#      - script: ./Scripts/BuildPhases/
#      name: "Firebase Settings"
#    preBuildScripts:
#      - script: ./Scripts/BuildPhases/
#      name: "Version Settings"

#    postCompileScripts:
#      - script: ./Scripts/BuildPhases/
#      name: "Crashlytics run script"
#    postBuildScripts:
#      - script: ./Scripts/BuildPhases/
#    postBuildScripts:
#      - script: ${SRCROOT}/Pods/SwiftLint/swiftlint autocorrect\n${PODS_ROOT}/SwiftLint/swiftlint lint
#        name: "Swiftlint run script"

  AppTests:
    type: bundle.unit-test
    platform: iOS
#    sources: AppTests
    dependencies:
      - target: App
#    schemes: {}
  AppUITests:
    type: bundle.ui-testing
    platform: iOS
#    sources: AppUITests
    dependencies:
      - target: App
#    schemes: {}

#fileGroups:
#  - README.md

schemes:
  SampleApplication-iOS: # TODO same Project name
    build:
      targets:
        App: all
    run:
      config: Debug # TODO same configs
      commandLineArguments:
        -FIRDebugEnabled: YES
        -FIRAnalyticsDebugEnabled: YES
        -FIRAnalyticsVerboseLoggingEnabled: YES
    test:
      config: Debug
      commandLineArguments:
        -FIRDebugEnabled: YES
        -FIRAnalyticsDebugEnabled: YES
        -FIRAnalyticsVerboseLoggingEnabled: YES
      gatherCoverageData: true
      targets:
        - name: AppTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: false

#  App Develop:
#    build:
#      targets:
#        App: all
#    run:
#      config: Develop Debug
#      commandLineArguments:
#        -FIRDebugEnabled: YES
#        -FIRAnalyticsDebugEnabled: YES
#        -FIRAnalyticsVerboseLoggingEnabled: YES
#    test:
#      config: Develop Debug
#      commandLineArguments:
#        -FIRDebugEnabled: YES
#        -FIRAnalyticsDebugEnabled: YES
#        -FIRAnalyticsVerboseLoggingEnabled: YES
#      gatherCoverageData: true
#      targets:
#        - name: AppTests
#          parallelizable: true
#          randomExecutionOrder: true
#    profile:
#      config: Develop Release
#    analyze:
#      config: Develop Debug
#    archive:
#      config: Develop Release
#      revealArchiveInOrganizer: false
#  App Staging:
#    build:
#      targets:
#        App: all
#    run:
#      config: Staging Debug
#      commandLineArguments:
#        -FIRDebugEnabled: YES
#        -FIRAnalyticsDebugEnabled: YES
#        -FIRAnalyticsVerboseLoggingEnabled: YES
#    test:
#      config: Staging Debug
#      commandLineArguments:
#        -FIRDebugEnabled: YES
#        -FIRAnalyticsDebugEnabled: YES
#        -FIRAnalyticsVerboseLoggingEnabled: YES
#      gatherCoverageData: true
#      targets:
#        - name: AppTests
#          parallelizable: true
#          randomExecutionOrder: true
#    profile:
#      config: Staging Release
#    analyze:
#      config: Staging Debug
#    archive:
#      config: Staging Release
#      revealArchiveInOrganizer: true
#  App Production:
#    build:
#      targets:
#        App: all
#    run:
#      config: Production Debug
#      commandLineArguments:
#        -FIRDebugEnabled: NO
#        -FIRAnalyticsDebugEnabled: NO
#        -FIRAnalyticsVerboseLoggingEnabled: NO
#    test:
#      config: Production Debug
#      commandLineArguments:
#        -FIRDebugEnabled: YES
#        -FIRAnalyticsDebugEnabled: YES
#        -FIRAnalyticsVerboseLoggingEnabled: YES
#      gatherCoverageData: true
#      targets:
#        - name: AppTests
#          parallelizable: true
#          randomExecutionOrder: true
#    profile:
#      config: Production Release
#    analyze:
#      config: Production Debug
#    archive:
#      config: Production Release
#      revealArchiveInOrganizer: true

#targetTemplates:

#packages:

#localPackages:

#projectReferences:
